# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b5959e0e69126dfd56844d243ba3e1b606254ff4bcabc4a6cdd8bc07f983946f3c6f077938984877f64d4303c8e5bae3e968b8d2b2c2a54daadd6cd2482ae0f

test:
  secret_key_base: 9014489e9ca0d66850cac71b7350532f344757c65c0d27ab07fd95fc550de6f307f9b8ac19e7224d5ac328e1ae2b8717c09e79d08d79451f04321a0d6fa9fa6f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
